# https://github.com/elastic/kibana-docker
#FROM kibana:5.3.0 # deprecated images https://github.com/deviantony/docker-elk/issues/119
FROM docker.elastic.co/kibana/kibana:5.3.0

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
