# https://github.com/elastic/logstash-docker
#FROM logstash:5.3.0 # deprecated images https://github.com/deviantony/docker-elk/issues/119
FROM docker.elastic.co/logstash/logstash:5.3.0

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
